### PR TITLE
XACML 4.0 draft - alternative formatting for definition lists (e.g. Glossary)

### PR DESCRIPTION
**Pull request by cdanger**
Proposing alternative formatting for the definition lists / indented paragraphs without using bullets in the HTML output. In the Markdown, this means replacing `* some_definition` with `: some_definition` and in the pandoc command line, replace  `gfm` with `gfm+definition_lists` to enable pandoc's [`definition_lists` extension](https://pandoc.org/MANUAL.html#definition-lists) .
See **_Files changed_** tab for more details.
Check [here](https://cdanger.github.io/xacml-spec/xacml-v4.0-csd01+definition_lists.html#12-glossary) for the HTML result (same as before without bullets).

In this PR, I have applied the changes only to the Glossary to show how it looks before applying to other definition lists in the doc. 

The only downside is the Github's markdown viewer which does not recognize this syntax, it will just show the colon characters (:) _as is_ on github.  Only pandoc will give the correct HTML result. Do you see this as an issue?

### CODE REVIEW

**Comment by humantypo** [comment]
IMG_8580

It appears that the first line is indented but not subsequent lines? Or is that an artifact of viewing on my phone?

**Comment by cdanger** [comment]
Could you force a reload/refresh of the page?
And let me know if you still have the issue. It's probably the old version of the page which is still in cache, because I did a previous attempt with this issue. But now it works on my side in Firefox, Chrome and Edge. I don't have Safari.
Are you using Safari?

**Comment by humantypo** [comment]
Took another look on my Mac. I use Brave (Chrome variant) on both, but I think I know what was causing it: The view above is the github "delta" view (just realized that from seeing green bars) that's showing what's changed. In looking at the "clean" view it looks good! 

Guess it pays to be "messy" once in a while in the threads by pasting images 😄 

Screenshot 2024-09-29 at 7 40 13 AM

**Review by steven-legg — APPROVED** [review]
Looks good.

**Comment by Hal-Lockhart** [comment]
#39 looks good to me..

Hal

**Pull request merged**
